sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

before_install:
  - docker pull mmhelloworld/idris:1.0
  - mkdir -p $HOME/bin/idris-packages $HOME/bin/idris-jvm
  - wget https://github.com/mmhelloworld/idris-jvm/releases/download/1.0-SNAPSHOT-20170520/idris-jvm-1.0-SNAPSHOT-20170520.zip
  - unzip -o idris-jvm-1.0-SNAPSHOT-20170520.zip -d $HOME/bin/idris-jvm
  - export PATH=`pwd`/bin/travis:$HOME/bin/idris-jvm/codegen/bin:$HOME/.local/bin:$PATH
  - export PROJECT_ROOT=`pwd`

script:
  - mvn -pl :idris-jvm-integration-test test -B